# 网络配置
network:
  host: localhost
  port: 8080
  buffer_size: 4096
  timeout: 1.0
  reconnect_interval: 5.0
  max_retries: 3

# 运动学配置
kinematics:
  dh_params:
    - theta: 0
      d: 0.1
      a: 0
      alpha: 1.5708
    - theta: 0
      d: 0
      a: 0.2
      alpha: 0
  joint_limits:
    - [-3.14, 3.14]
    - [-1.57, 1.57]
  planning_freq: 100
  max_velocity: 1.0
  max_acceleration: 2.0

# 动力学配置
dynamics:
  dynamics_params:
    link_1:
      mass: 1.0
      inertia: [[0.1, 0, 0], [0, 0.1, 0], [0, 0, 0.1]]
      com: [0, 0, 0.5]
      damping: 0.1
      friction: 0.1
    link_2:
      mass: 0.8
      inertia: [[0.08, 0, 0], [0, 0.08, 0], [0, 0, 0.08]]
      com: [0, 0, 0.4]
      damping: 0.1
      friction: 0.1

# 控制器配置
controller:
  gains:
    kp: [100.0, 100.0]
    kd: [20.0, 20.0]
    ki: [1.0, 1.0]
  control_freq: 1000
  timeout: 0.1

# 传感器配置
sensors:
  imu:
    type: mpu6050
    address: 0x68
    sample_rate: 100
  encoder:
    type: abs_encoder
    resolution: 4096
    sample_rate: 1000

# 执行器配置
actuators:
  joint_1:
    type: dc_motor
    max_torque: 1.0
    max_velocity: 6.28
  joint_2:
    type: dc_motor
    max_torque: 0.8
    max_velocity: 6.28

# 日志配置
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: logs/robot.log
  max_size: 10485760  # 10MB
  backup_count: 5

# 网络安全配置
security:
  secret_key: ""  # 留空自动生成
  enable_encryption: true
  enable_auth: true
  token_expire: 3600

# 心跳配置
heartbeat:
  interval: 5.0  # 心跳间隔(秒)
  timeout: 15.0  # 超时时间(秒)
  max_missed: 3  # 最大丢失次数

# 连接池配置
connection_pool:
  max_size: 10  # 最大连接数
  min_size: 2   # 最小连接数
  timeout: 30.0 # 连接超时时间
  max_idle: 300 # 最大空闲时间(秒)
  max_lifetime: 3600 # 最大生存时间(秒)

# 负载均衡配置
load_balancer:
  check_interval: 30
  fail_timeout: 30
  max_fails: 3
  nodes:
    - host: localhost
      port: 8081
      weight: 1
    - host: localhost
      port: 8082
      weight: 1

# 任务队列配置
task_queue:
  worker_count: 4  # 工作线程数
  default_timeout: 60.0  # 默认超时时间
  max_retries: 3  # 最大重试次数

# 压缩配置
compression:
  type: lz4  # none/zlib/lz4/snappy
  level: 6
  min_size: 1024

# 缓存配置
cache:
  type: ttl  # ttl/lru
  max_size: 1000
  ttl: 300

# 流量控制配置
rate_limit:
  max_requests: 100
  window_size: 60
  burst_size: 10

# 轨迹优化配置
model:
  trajectory:
    max_iterations: 100
    tolerance: 1e-6
    constraints_weight: 1.0
    smoothness_weight: 0.5
    method: SLSQP 